spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yumengjie2018/spring-config/blob/master/config.yml
          username: yumengjie2018
          password: 2018yumengjie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8891/eureka/

  instance:
      prefer-ip-address: true
      #指定注册中心显示的IP
      instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
server:
  port: 8892
