server:
  port: 9988
spring:
  application:
    name: jlAppService
    zhname: 吉林掌上网优

  datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://124.89.119.46:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#        username: root
#        password: Boco@123
        url: jdbc:oracle:thin:@//10.10.2.31:1521/orcl
        username: niosuser_yunnan
        password: niosuser_yunnan
    #数据库驱动
        driver-class-name: oracle.jdbc.driver.OracleDriver
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5

  servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB

#XML路径配置
mybatis:
  mapperLocations: classpath:mybatis/mapper/default/*.xml
  type-aliases-package: com.boco.jlappservice.entity
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#Swagger开关
swaggerEnable: true
#发布的服务器IP地址
publicServer:
  address: http://124.89.119.46:9988
