spring:
  profiles:
    active: dev
  application:
    name: testservie
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//10.10.2.31:1521/orcl
      username: osmp_ah
      password: osmp_ah
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.132.52.154:1521:wytymh
#    username: wyniosdb
#    password: Sxwy12cdb
#  jpa:
#    hibernate:
#          ddl-auto: update #自动更新
#    show-sql: true  #日志中显示sql语句
#debug: true
  #Redis
  #spring.redis.host=127.0.0.1



server:
  port: 9988

#XML文件位置ybatis:
mybatis:
  mapperLocations: classpath*:mybatis/mapper/default/**/*.xml
  type-aliases-package: com.example.service.entity
  configuration:
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
          variables:
            userId: 3c9b1d04-c1a7-471f-9c52-62693127acfb

#Swagger开关
swaggerEnable: true

# 分页配置
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #日志打印配置
logging:
  level:
    root: info
  file: logs/sys.log

