server:
  port: 9997
spring:
  jpa:
    database: oracle
#    hibernate:
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  redis:
      host: 127.0.0.1
    ## Redis服务器连接端口
      port: 6379
    ## 连接超时时间（毫秒）
      timeout: 3s
    ## Redis服务器连接密码（默认为空）
      password: yumengjie
    ## 连接池中的最大连接数
      poolMaxTotal: 10
    ## 连接池中的最大空闲连接
      poolMaxIdle: 10
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      poolMaxWait: 3
      jedis:
        pool:
          min-idle: 5
          max-idle: 10
          max-wait: 20s
          max-active: 8
  cache:
    type: redis
    cache-names: redisCache,hashCache
