server:
  port: 9888
spring:
  application:
    name: hnAppService
  datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//10.10.2.31:1521/orcl
        username: osmp_ah
        password: osmp_ah
  #文件上传下载大小
  servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB

#XML文件位置
mybatis:
  mapperLocations: classpath:mybatis/mapper/default/*.xml
  type-aliases-package: com.boco.hnappservice.entity
#Swagger开关
swaggerEnable: true

